spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    h2:
      console:
        enabled: true

fileRepositoryFolder: D:\\FABIO\\INFORMATICA\\Develhope\\Java\\Java-Exercises\\Lessons\\UploadDownloadFilesRepository
